//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceSwitch.Extension.Palette.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SourceSwitch.Extension.Palette.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch input source.
        /// </summary>
        internal static string CommandsProvider_CommandsProvider_Switch_input_source {
            get {
                return ResourceManager.GetString("CommandsProvider_CommandsProvider_Switch_input_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch the current monitor&apos;s input source..
        /// </summary>
        internal static string CommandsProvider_CommandsProvider_Switch_the_current_monitor_s_input_source_ {
            get {
                return ResourceManager.GetString("CommandsProvider_CommandsProvider_Switch_the_current_monitor_s_input_source_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to {0}.
        /// </summary>
        internal static string MainPage_GetItems_Switch_to__0_ {
            get {
                return ResourceManager.GetString("MainPage_GetItems_Switch_to__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch input source.
        /// </summary>
        internal static string MainPage_MainPage_Switch_input_source {
            get {
                return ResourceManager.GetString("MainPage_MainPage_Switch_input_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the input source configuration. Use TOML format..
        /// </summary>
        internal static string SettingsManager__inputSourceOrder_Adjust_the_input_source_configuration__Use_TOML_format_ {
            get {
                return ResourceManager.GetString(("SettingsManager__inputSourceOrder_Adjust_the_input_source_configuration__Use_TOML" +
                        "_format_"), resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input source configuration.
        /// </summary>
        internal static string SettingsManager__inputSourceOrder_Input_source_configuration {
            get {
                return ResourceManager.GetString("SettingsManager__inputSourceOrder_Input_source_configuration", resourceCulture);
            }
        }
    }
}
